# This is a basic workflow to help you get started with Actions

name: Angular CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
      - uses: actions/checkout@v3
      # Install NodeJS
      - name: Install NodeJS
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "18"
      # Install dependencies
      - name: Install dependencies
        run: npm i
      # Build application for production
      - name: Build app bundle
        run: npm run build:prod
      # Deploy to GitHub Pages
      - name: Deployment to Pages
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          build_dir: dist/pokeapp
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
